server:
  port: 8803
#  port: ${random.int[10000,19999]} #随机端口

spring:
  application:
    name: spring-cloud-consumer



# 手写rpc todof
#spring:
#  rpc:
#    register-address: localhost:2181
#    module-name: customer



