server:
  port: 8804
#  port: ${random.int[10000,19999]} #随机端口

spring:
  application:
    name: spring-cloud-consumer



rpc:
  registerAddress: localhost:2181
  port: ${random.int[10000,19999]}
  moduleName: spring-cloud-consumer
  timeout: 2000



