server:
  port: 8803
  tomcat:
    relaxed-path-chars:
#  port: ${random.int[10000,19999]} #随机端口

spring:
  application:
    name: spring-cloud-consul
  rabbitmq:
    publisher-confirm-type:


rpc:
  registerAddress: localhost:2181
  port: ${random.int[10000,19999]}
  moduleName: spring-cloud-consul
  timeout: 2000
